version: '3.9'

services:
  db:
    image: postgres:15
    container_name: desafio2_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: desafio2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./carros.sql:/docker-entrypoint-initdb.d/carros.sql

  reader:
    build: .
    container_name: desafio2_reader
    depends_on:
      - db
    ports:
      - "5000:5000"
    restart: always

volumes:
  pgdata:
